services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: smartlearn_db
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      DB_NAME: smartlearn_db
      DB_USER: yourusername
      DB_PASSWORD: yourpassword
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
